CONFIG_GPIO=y
CONFIG_GPIO_HOGS=y

CONFIG_MAIN_STACK_SIZE=512
CONFIG_ISR_STACK_SIZE=1024
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=512
CONFIG_HEAP_MEM_POOL_SIZE=0

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_ASYNC_API=y

CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_BACKEND_UART_ASYNC=y
CONFIG_LOG_BACKEND_UART_BUFFER_SIZE=128
CONFIG_LOG_BUFFER_SIZE=1024
CONFIG_LOG_PROCESS_THREAD_CUSTOM_PRIORITY=y
CONFIG_LOG_PROCESS_THREAD_PRIORITY=6
CONFIG_LOG_BLOCK_IN_THREAD=n
CONFIG_LOG_MODE_OVERFLOW=y
CONFIG_LOG_PRINTK=y

CONFIG_PRINTK=y
CONFIG_BOOT_BANNER=y

CONFIG_COMPILER_WARNINGS_AS_ERRORS=y
CONFIG_BUILD_OUTPUT_BIN=y
CONFIG_BUILD_OUTPUT_HEX=y
